name: ci
on:
   pull_request:
   push:
      branches: [master]
jobs:
   lint-and-typecheck:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
              node-version-file: '.nvmrc'
              cache: 'npm'
         - name: Cache node_modules/.cache directory
           uses: actions/cache@v3
           with:
              path: node_modules/.cache
              key: node-modules-dot-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ github.run_id }}
              restore-keys: |
                 node-modules-dot-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-
         - run: npm run eslint
         - run: npm run prettier
         - run: npm test
         - run: npx tsc
